// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weblog_record.proto

package com.packt.hadoop.hdfs.ch2.protobuf;

public final class WeblogRecord {
  private WeblogRecord() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Record extends
      com.google.protobuf.GeneratedMessage {
    // Use Record.newBuilder() to construct.
    private Record() {
      initFields();
    }
    private Record(boolean noInit) {}
    
    private static final Record defaultInstance;
    public static Record getDefaultInstance() {
      return defaultInstance;
    }
    
    public Record getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.packt.hadoop.hdfs.ch2.protobuf.WeblogRecord.internal_static_example_Record_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.packt.hadoop.hdfs.ch2.protobuf.WeblogRecord.internal_static_example_Record_fieldAccessorTable;
    }
    
    // optional string cookie = 1;
    public static final int COOKIE_FIELD_NUMBER = 1;
    private boolean hasCookie;
    private java.lang.String cookie_ = "";
    public boolean hasCookie() { return hasCookie; }
    public java.lang.String getCookie() { return cookie_; }
    
    // required string page = 2;
    public static final int PAGE_FIELD_NUMBER = 2;
    private boolean hasPage;
    private java.lang.String page_ = "";
    public boolean hasPage() { return hasPage; }
    public java.lang.String getPage() { return page_; }
    
    // required int64 timestamp = 3;
    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private boolean hasTimestamp;
    private long timestamp_ = 0L;
    public boolean hasTimestamp() { return hasTimestamp; }
    public long getTimestamp() { return timestamp_; }
    
    // required string ip = 4;
    public static final int IP_FIELD_NUMBER = 4;
    private boolean hasIp;
    private java.lang.String ip_ = "";
    public boolean hasIp() { return hasIp; }
    public java.lang.String getIp() { return ip_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasPage) return false;
      if (!hasTimestamp) return false;
      if (!hasIp) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasCookie()) {
        output.writeString(1, getCookie());
      }
      if (hasPage()) {
        output.writeString(2, getPage());
      }
      if (hasTimestamp()) {
        output.writeInt64(3, getTimestamp());
      }
      if (hasIp()) {
        output.writeString(4, getIp());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCookie()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getCookie());
      }
      if (hasPage()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getPage());
      }
      if (hasTimestamp()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, getTimestamp());
      }
      if (hasIp()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getIp());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.packt.hadoop.hdfs.ch2.protobuf.WeblogRecord.Record parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.packt.hadoop.hdfs.ch2.protobuf.WeblogRecord.Record parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.packt.hadoop.hdfs.ch2.protobuf.WeblogRecord.Record parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.packt.hadoop.hdfs.ch2.protobuf.WeblogRecord.Record parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.packt.hadoop.hdfs.ch2.protobuf.WeblogRecord.Record parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.packt.hadoop.hdfs.ch2.protobuf.WeblogRecord.Record parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.packt.hadoop.hdfs.ch2.protobuf.WeblogRecord.Record parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.packt.hadoop.hdfs.ch2.protobuf.WeblogRecord.Record parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.packt.hadoop.hdfs.ch2.protobuf.WeblogRecord.Record parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.packt.hadoop.hdfs.ch2.protobuf.WeblogRecord.Record parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.packt.hadoop.hdfs.ch2.protobuf.WeblogRecord.Record prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.packt.hadoop.hdfs.ch2.protobuf.WeblogRecord.Record result;
      
      // Construct using com.packt.hadoop.hdfs.ch2.protobuf.WeblogRecord.Record.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.packt.hadoop.hdfs.ch2.protobuf.WeblogRecord.Record();
        return builder;
      }
      
      protected com.packt.hadoop.hdfs.ch2.protobuf.WeblogRecord.Record internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.packt.hadoop.hdfs.ch2.protobuf.WeblogRecord.Record();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.packt.hadoop.hdfs.ch2.protobuf.WeblogRecord.Record.getDescriptor();
      }
      
      public com.packt.hadoop.hdfs.ch2.protobuf.WeblogRecord.Record getDefaultInstanceForType() {
        return com.packt.hadoop.hdfs.ch2.protobuf.WeblogRecord.Record.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.packt.hadoop.hdfs.ch2.protobuf.WeblogRecord.Record build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.packt.hadoop.hdfs.ch2.protobuf.WeblogRecord.Record buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.packt.hadoop.hdfs.ch2.protobuf.WeblogRecord.Record buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.packt.hadoop.hdfs.ch2.protobuf.WeblogRecord.Record returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.packt.hadoop.hdfs.ch2.protobuf.WeblogRecord.Record) {
          return mergeFrom((com.packt.hadoop.hdfs.ch2.protobuf.WeblogRecord.Record)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.packt.hadoop.hdfs.ch2.protobuf.WeblogRecord.Record other) {
        if (other == com.packt.hadoop.hdfs.ch2.protobuf.WeblogRecord.Record.getDefaultInstance()) return this;
        if (other.hasCookie()) {
          setCookie(other.getCookie());
        }
        if (other.hasPage()) {
          setPage(other.getPage());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasIp()) {
          setIp(other.getIp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setCookie(input.readString());
              break;
            }
            case 18: {
              setPage(input.readString());
              break;
            }
            case 24: {
              setTimestamp(input.readInt64());
              break;
            }
            case 34: {
              setIp(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional string cookie = 1;
      public boolean hasCookie() {
        return result.hasCookie();
      }
      public java.lang.String getCookie() {
        return result.getCookie();
      }
      public Builder setCookie(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasCookie = true;
        result.cookie_ = value;
        return this;
      }
      public Builder clearCookie() {
        result.hasCookie = false;
        result.cookie_ = getDefaultInstance().getCookie();
        return this;
      }
      
      // required string page = 2;
      public boolean hasPage() {
        return result.hasPage();
      }
      public java.lang.String getPage() {
        return result.getPage();
      }
      public Builder setPage(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPage = true;
        result.page_ = value;
        return this;
      }
      public Builder clearPage() {
        result.hasPage = false;
        result.page_ = getDefaultInstance().getPage();
        return this;
      }
      
      // required int64 timestamp = 3;
      public boolean hasTimestamp() {
        return result.hasTimestamp();
      }
      public long getTimestamp() {
        return result.getTimestamp();
      }
      public Builder setTimestamp(long value) {
        result.hasTimestamp = true;
        result.timestamp_ = value;
        return this;
      }
      public Builder clearTimestamp() {
        result.hasTimestamp = false;
        result.timestamp_ = 0L;
        return this;
      }
      
      // required string ip = 4;
      public boolean hasIp() {
        return result.hasIp();
      }
      public java.lang.String getIp() {
        return result.getIp();
      }
      public Builder setIp(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasIp = true;
        result.ip_ = value;
        return this;
      }
      public Builder clearIp() {
        result.hasIp = false;
        result.ip_ = getDefaultInstance().getIp();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:example.Record)
    }
    
    static {
      defaultInstance = new Record(true);
      com.packt.hadoop.hdfs.ch2.protobuf.WeblogRecord.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:example.Record)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_example_Record_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_example_Record_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023weblog_record.proto\022\007example\"E\n\006Record" +
      "\022\016\n\006cookie\030\001 \001(\t\022\014\n\004page\030\002 \002(\t\022\021\n\ttimest" +
      "amp\030\003 \002(\003\022\n\n\002ip\030\004 \002(\tB2\n\"com.packt.hadoo" +
      "p.hdfs.ch2.protobufB\014WeblogRecord"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_example_Record_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_example_Record_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_example_Record_descriptor,
              new java.lang.String[] { "Cookie", "Page", "Timestamp", "Ip", },
              com.packt.hadoop.hdfs.ch2.protobuf.WeblogRecord.Record.class,
              com.packt.hadoop.hdfs.ch2.protobuf.WeblogRecord.Record.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
